"""create_finance_schema

Revision ID: e016133c0a3b
Revises: 
Create Date: 2026-08-27 06:01:36.488658
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e016133c0a3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='user_role', native_enum=False, length=16), nullable=False),
    sa.Column('admin_claim', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('admin_claim IS NULL OR admin_claim = true', name='ck_app_user_admin_claim_true'),
    sa.CheckConstraint('length(email) > 3', name='ck_app_user_email_len'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_claim', name='uq_app_user_admin_claim'),
    sa.UniqueConstraint('email', name='uq_app_user_email')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=False)
    op.create_index('ix_app_user_role', 'app_user', ['role'], unique=False)
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(base_currency) = 3', name='ck_portfolio_currency_len'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_portfolio_user_id')
    )
    op.create_index(op.f('ix_portfolio_user_id'), 'portfolio', ['user_id'], unique=False)
    op.create_table('user_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_user_session_token_hash')
    )
    op.create_index('ix_user_session_user_expires', 'user_session', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_user_session_user_id'), 'user_session', ['user_id'], unique=False)
    op.create_table('holding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('asset_type', sa.Enum('EQUITY', 'ETF', 'BOND', 'CRYPTO', 'CASH', 'COMMODITY', 'REAL_ESTATE', 'OTHER', name='asset_type', native_enum=False, length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_price >= 0', name='ck_holding_current_price'),
    sa.CheckConstraint('purchase_price >= 0', name='ck_holding_purchase_price'),
    sa.CheckConstraint('quantity > 0', name='ck_holding_quantity_positive'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_holding_asset_type', 'holding', ['asset_type'], unique=False)
    op.create_index(op.f('ix_holding_portfolio_id'), 'holding', ['portfolio_id'], unique=False)
    op.create_index('ix_holding_portfolio_symbol', 'holding', ['portfolio_id', 'symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_holding_portfolio_symbol', table_name='holding')
    op.drop_index(op.f('ix_holding_portfolio_id'), table_name='holding')
    op.drop_index('ix_holding_asset_type', table_name='holding')
    op.drop_table('holding')
    op.drop_index(op.f('ix_user_session_user_id'), table_name='user_session')
    op.drop_index('ix_user_session_user_expires', table_name='user_session')
    op.drop_table('user_session')
    op.drop_index(op.f('ix_portfolio_user_id'), table_name='portfolio')
    op.drop_table('portfolio')
    op.drop_index('ix_app_user_role', table_name='app_user')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
